export const CurrenciesList = [
  { code: "JOD", name: "Jordanian dinar", symbol: "د.ا" },
  { code: "USD", name: "United States dollar", symbol: "$" },
  { code: "RSD", name: "Serbian dinar", symbol: "дин." },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "BMD", name: "Bermudian dollar", symbol: "$" },
  { code: "BOB", name: "Bolivian boliviano", symbol: "Bs." },
  { code: "LYD", name: "Libyan dinar", symbol: "ل.د" },
  { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
  { code: "AMD", name: "Armenian dram", symbol: "֏" },
  { code: "MUR", name: "Mauritian rupee", symbol: "₨" },
  { code: "MVR", name: "Maldivian rufiyaa", symbol: ".ރ" },
  { code: "MKD", name: "denar", symbol: "den" },
  { code: "ETB", name: "Ethiopian birr", symbol: "Br" },
  { code: "DKK", name: "krone", symbol: "kr." },
  { code: "IQD", name: "Iraqi dinar", symbol: "ع.د" },
  { code: "GTQ", name: "Guatemalan quetzal", symbol: "Q" },
  { code: "TTD", name: "Trinidad and Tobago dollar", symbol: "$" },
  { code: "PEN", name: "Peruvian sol", symbol: "S/ " },
  { code: "SRD", name: "Surinamese dollar", symbol: "$" },
  { code: "SEK", name: "Swedish krona", symbol: "kr" },
  { code: "XPF", name: "CFP franc", symbol: "₣" },
  { code: "FKP", name: "Falkland Islands pound", symbol: "£" },
  { code: "ZWL", name: "Zimbabwean dollar", symbol: "$" },
  { code: "SAR", name: "Saudi riyal", symbol: "ر.س" },
  { code: "AED", name: "United Arab Emirates dirham", symbol: "د.إ" },
  { code: "AFN", name: "Afghan afghani", symbol: "؋" },
  { code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
  { code: "PAB", name: "Panamanian balboa", symbol: "B/." },
  { code: "SYP", name: "Syrian pound", symbol: "£" },
  { code: "VUV", name: "Vanuatu vatu", symbol: "Vt" },
  { code: "HNL", name: "Honduran lempira", symbol: "L" },
  { code: "AUD", name: "Australian dollar", symbol: "$" },
  { code: "CLP", name: "Chilean peso", symbol: "$" },
  { code: "XCD", name: "Eastern Caribbean dollar", symbol: "$" },
  { code: "MXN", name: "Mexican peso", symbol: "$" },
  { code: "CNY", name: "Chinese yuan", symbol: "¥" },
  { code: "SSP", name: "South Sudanese pound", symbol: "£" },
  { code: "SZL", name: "Swazi lilangeni", symbol: "L" },
  { code: "UZS", name: "Uzbekistani soʻm", symbol: "so'm" },
  { code: "IDR", name: "Indonesian rupiah", symbol: "Rp" },
  { code: "PYG", name: "Paraguayan guaraní", symbol: "₲" },
  { code: "PLN", name: "Polish złoty", symbol: "zł" },
  { code: "BAM", name: "Bosnia and Herzegovina convertible mark", symbol: "B" },
  { code: "CAD", name: "Canadian dollar", symbol: "$" },
  { code: "BRL", name: "Brazilian real", symbol: "R$" },
  { code: "MRU", name: "Mauritanian ouguiya", symbol: "UM" },
  { code: "ILS", name: "Israeli new shekel", symbol: "₪" },
  { code: "ANG", name: "Netherlands Antillean guilder", symbol: "ƒ" },
  { code: "BND", name: "Brunei dollar", symbol: "$" },
  { code: "AOA", name: "Angolan kwanza", symbol: "Kz" },
  { code: "BYN", name: "Belarusian ruble", symbol: "Br" },
  { code: "TRY", name: "Turkish lira", symbol: "₺" },
  { code: "GIP", name: "Gibraltar pound", symbol: "£" },
  { code: "BTN", name: "Bhutanese ngultrum", symbol: "Nu." },
  { code: "VES", name: "Venezuelan bolívar soberano", symbol: "Bs.S." },
  { code: "QAR", name: "Qatari riyal", symbol: "ر.ق" },
  { code: "CZK", name: "Czech koruna", symbol: "Kč" },
  { code: "KWD", name: "Kuwaiti dinar", symbol: "د.ك" },
  { code: "INR", name: "Indian rupee", symbol: "₹" },
  { code: "NZD", name: "New Zealand dollar", symbol: "$" },
  { code: "JMD", name: "Jamaican dollar", symbol: "$" },
  { code: "KYD", name: "Cayman Islands dollar", symbol: "$" },
  { code: "PKR", name: "Pakistani rupee", symbol: "₨" },
  { code: "KZT", name: "Kazakhstani tenge", symbol: "₸" },
  { code: "BHD", name: "Bahraini dinar", symbol: ".د.ب" },
  { code: "FJD", name: "Fijian dollar", symbol: "$" },
  { code: "ISK", name: "Icelandic króna", symbol: "kr" },
  { code: "MMK", name: "Burmese kyat", symbol: "Ks" },
  { code: "BDT", name: "Bangladeshi taka", symbol: "৳" },
  { code: "PHP", name: "Philippine peso", symbol: "₱" },
  { code: "NPR", name: "Nepalese rupee", symbol: "₨" },
  { code: "YER", name: "Yemeni rial", symbol: "﷼" },
  { code: "KRW", name: "South Korean won", symbol: "₩" },
  { code: "OMR", name: "Omani rial", symbol: "ر.ع." },
  { code: "ERN", name: "Eritrean nakfa", symbol: "Nfk" },
  { code: "IRR", name: "Iranian rial", symbol: "﷼" },
  { code: "TZS", name: "Tanzanian shilling", symbol: "Sh" },
  { code: "SBD", name: "Solomon Islands dollar", symbol: "$" },
  { code: "KES", name: "Kenyan shilling", symbol: "Sh" },
  { code: "DOP", name: "Dominican peso", symbol: "$" },
  { code: "GBP", name: "British pound", symbol: "£" },
  { code: "RWF", name: "Rwandan franc", symbol: "Fr" },
  { code: "TWD", name: "New Taiwan dollar", symbol: "$" },
  { code: "GYD", name: "Guyanese dollar", symbol: "$" },
  { code: "SCR", name: "Seychellois rupee", symbol: "₨" },
  { code: "KPW", name: "North Korean won", symbol: "₩" },
  { code: "BWP", name: "Botswana pula", symbol: "P" },
  { code: "KHR", name: "Cambodian riel", symbol: "៛" },
  { code: "BBD", name: "Barbadian dollar", symbol: "$" },
  { code: "COP", name: "Colombian peso", symbol: "$" },
  { code: "UAH", name: "Ukrainian hryvnia", symbol: "₴" },
  { code: "NAD", name: "Namibian dollar", symbol: "$" },
  { code: "TOP", name: "Tongan paʻanga", symbol: "T$" },
  { code: "ARS", name: "Argentine peso", symbol: "$" },
  { code: "CRC", name: "Costa Rican colón", symbol: "₡" },
  { code: "GHS", name: "Ghanaian cedi", symbol: "₵" },
  { code: "EGP", name: "Egyptian pound", symbol: "E£" },
  { code: "CUC", name: "Cuban convertible peso", symbol: "$" },
  { code: "HUF", name: "Hungarian forint", symbol: "Ft" },
  { code: "BZD", name: "Belize dollar", symbol: "$" },
  { code: "BSD", name: "Bahamian dollar", symbol: "$" },
  { code: "AWG", name: "Aruban florin", symbol: "ƒ" },
  { code: "STN", name: "São Tomé and Príncipe dobra", symbol: "Db" },
  { code: "RUB", name: "Russian ruble", symbol: "₽" },
  { code: "NIO", name: "Nicaraguan córdoba", symbol: "C$" },
  { code: "TND", name: "Tunisian dinar", symbol: "د.ت" },
  { code: "CDF", name: "Congolese franc", symbol: "FC" },
  { code: "NOK", name: "krone", symbol: "kr" },
  { code: "ZAR", name: "South African rand", symbol: "R" },
  { code: "SLL", name: "Sierra Leonean leone", symbol: "Le" },
  { code: "LSL", name: "Lesotho loti", symbol: "L" },
  { code: "SHP", name: "Saint Helena pound", symbol: "£" },
  { code: "DJF", name: "Djiboutian franc", symbol: "Fr" },
  { code: "LKR", name: "Sri Lankan rupee", symbol: "Rs  රු" },
  { code: "WST", name: "Samoan tālā", symbol: "T" },
  { code: "TMT", name: "Turkmenistan manat", symbol: "m" },
  { code: "MDL", name: "Moldovan leu", symbol: "L" },
  { code: "CHF", name: "Swiss franc", symbol: "Fr" },
  { code: "MWK", name: "Malawian kwacha", symbol: "MK" },
  { code: "LBP", name: "Lebanese pound", symbol: "ل.ل" },
  { code: "MNT", name: "Mongolian tögrög", symbol: "₮" },
  { code: "THB", name: "Thai baht", symbol: "฿" },
  { code: "NGN", name: "Nigerian naira", symbol: "₦" },
  { code: "CVE", name: "Cape Verdean escudo", symbol: "Esc" },
  { code: "DZD", name: "Algerian dinar", symbol: "د.ج" },
  { code: "LAK", name: "Lao kip", symbol: "₭" },
  { code: "AZN", name: "Azerbaijani manat", symbol: "₼" },
  { code: "MAD", name: "Moroccan dirham", symbol: "د.م." },
  { code: "BGN", name: "Bulgarian lev", symbol: "лв" },
  { code: "BIF", name: "Burundian franc", symbol: "Fr" },
  { code: "UGX", name: "Ugandan shilling", symbol: "Sh" },
  { code: "MZN", name: "Mozambican metical", symbol: "MT" },
  { code: "GEL", name: "lari", symbol: "₾" },
  { code: "RON", name: "Romanian leu", symbol: "lei" },
  { code: "VND", name: "Vietnamese đồng", symbol: "₫" },
  { code: "JPY", name: "Japanese yen", symbol: "¥" },
  { code: "LRD", name: "Liberian dollar", symbol: "$" },
  { code: "HTG", name: "Haitian gourde", symbol: "G" },
  { code: "PGK", name: "Papua New Guinean kina", symbol: "K" },
  { code: "HKD", name: "Hong Kong dollar", symbol: "$" },
  { code: "KGS", name: "Kyrgyzstani som", symbol: "с" },
  { code: "MGA", name: "Malagasy ariary", symbol: "Ar" },
  { code: "GMD", name: "dalasi", symbol: "D" },
  { code: "SGD", name: "Singapore dollar", symbol: "$" },
  { code: "MYR", name: "Malaysian ringgit", symbol: "RM" },
  { code: "SOS", name: "Somali shilling", symbol: "Sh" },
  { code: "MOP", name: "Macanese pataca", symbol: "P" },
  { code: "ALL", name: "Albanian lek", symbol: "L" },
  { code: "ZMW", name: "Zambian kwacha", symbol: "ZK" },
  { code: "CKD", name: "Cook Islands dollar", symbol: "$" },
  { code: "GNF", name: "Guinean franc", symbol: "Fr" },
  { code: "KMF", name: "Comorian franc", symbol: "Fr" },
  { code: "SDG", name: "Sudanese pound", symbol: "" },
  { code: "TJS", name: "Tajikistani somoni", symbol: "ЅМ" },
  { code: "UYU", name: "Uruguayan peso", symbol: "$" },
];
