export const paymentMethods = [
  "All",
  "Wallet Payment",
  "Bank Transfer",
  "Gift Card",
  "7-Eleven",
  "A-Bank",
  "ABA",
  "ABB Bank",
  "ABN AMRO",
  "Absolut Bank",
  "Abu Dhabi Commercial Bank ADCB",
  "Abyssinia",
  "ACBA Bank",
  "Access Bank",
  "Accordbank",
  "ACLEDA",
  "ADIB: Abu Dhabi Islamic Bank",
  "Advcash",
  "Advcash - Instant",
  "Afghanistan International Bank",
  "Afriland First Bank",
  "Afrimoney - Sierra Leone",
  "Agrobank",
  "Ahlibank",
  "Aircash",
  "Airtel Money",
  "Airtime Mobile Top-Up",
  "AirTM",
  "Aiyl Bank",
  "Ak Bars Bank",
  "Akbank",
  "Al Hilal Bank",
  "AL MASHREQ Bank",
  "Al Rajhi Bank",
  "Al-Rafidain QiServices",
  "Aladin Bank",
  "alBaraka",
  "Alef-Bank",
  "Alex Bank",
  "Alif Bank",
  "Alinma Bank",
  "Alior Bank",
  "Alipay",
  "Allied Bank Limited, Wholesale Branch",
  "Allo Bank",
  "Aloqa Bank",
  "Altaif Islamic Bank",
  "Altyn Bank",
  "AM BANK",
  "Amen Bank",
  "Ameriabank",
  "Amonatbonk",
  "Anorbank",
  "AnyCash",
  "ANZ",
  "Apelsin",
  "Arab African International Bank-AAIB",
  "Arab Bank",
  "Arab International Bank of Tunisia",
  "Arab Tunisian Bank",
  "AraratBank",
  "ArCA",
  "Ardshinbank",
  "Arig Bank",
  "ArmBusinessBank",
  "ArmEconomBank",
  "Artsakhbank",
  "Asaka Bank",
  "Asia Alliance Bank",
  "Asia Hawala",
  "Asia United Bank",
  "Atlantic Bank",
  "Attijari Bank",
  "Attijariwafa National Bank",
  "Awash",
  "AYA Pay",
  "Azer Turk Bank",
  "Azizi Bank",
  "BAC Banco America Central GT",
  "BAC Costa Rica",
  "BAC Credomatic",
  "BAC Credomatic Guatemala",
  "BAC Credomatic Honduras",
  "BAC Credomatic Nicaragua",
  "Bai-Tushum Bank",
  "Bakai Bank",
  "Bakong",
  "BAM Banco Agromercantil GT",
  "BanBif",
  "Bancamiga",
  "Bancaribe",
  "Banco Activo",
  "Banco Agricola SV",
  "Banco Atlantida",
  "Banco Atlas",
  "Banco Azteca Guatemala",
  "Banco BAC Credomatic SV",
  "Banco Basa",
  "Banco BHD",
  "Banco Bisa",
  "Banco Bolivariano",
  "Banco Brubank",
  "Banco Continental Paraguay",
  "Banco Davivienda SV",
  "Banco de Bogota",
  "Banco de Chile",
  "Banco de Costa Rica",
  "Banco de Credito",
  "Banco de desarrollo Rural",
  "Banco de Occidente Honduras",
  "Banco De Oro (BDO)",
  "Banco de Venezuela",
  "Banco del pacifico",
  "Banco del Sol",
  "Banco Economico",
  "Banco Estado",
  "Banco Falabella",
  "Banco Familiar",
  "Banco Fassil",
  "Banco Fucerep",
  "Banco G&T Continental",
  "Banco Ganadero",
  "Banco General Panama",
  "Banco GNB Paraguay",
  "Banco Guayaquil",
  "Banco Hipotecario SV",
  "Banco Industrial",
  "Banco Internacional",
  "Banco Itau Chile",
  "Banco Itau Paraguay",
  "Banco Lafise Nicaragua",
  "Banco Mercantil Santa Cruz",
  "Banco Nacional de Bolivia",
  "Banco Pichincha",
  "Banco Plaza",
  "Banco Popular",
  "Banco Promerica SV",
  "Banco Regional",
  "Banco Rio",
  "Banco Sabadell (Spain)",
  "Banco Santander (Spain)",
  "Banco Santander Argentina",
  "Banco Santander Chile",
  "Banco Santander Uruguay",
  "Banco Solidario",
  "Banco Union",
  "Bancolombia S.A",
  "Bancontact",
  "Bandes Uruguay",
  "Banesco",
  "Banesco Panama",
  "Banistmo Panama",
  "Bank Al Etihad",
  "Bank Audi",
  "Bank BRI",
  "Bank Credit Dnipro",
  "Bank Dhofar",
  "Bank Eskhata",
  "Bank Jago",
  "Bank Muscat",
  "Bank Nizwa",
  "Bank of America",
  "Bank of Asia",
  "Bank of Bahrain and Kuwait B.S.C.",
  "Bank of Beirut",
  "Bank of Georgia",
  "Bank of Jordan",
  "Bank of Khartoum",
  "Bank of the Bahamas Limited",
  "Bank of the Philippine Islands (BPI)",
  "Bank of the Republic of Uruguay",
  "Bank Pekao",
  "Bank Pivdenny",
  "Bank RBK",
  "Bank Reshenie",
  "Bank Respublika",
  "Bank Saint-Petersburg",
  "Bank Sampoerna",
  "Bank slip",
  "Bank Transfer",
  "Bank Transfer (Argentina)",
  "Bank Transfer (Brazil)",
  "Bank Transfer (Cambodia)",
  "Bank Transfer (Costa Rica)",
  "Bank Transfer (India)",
  "Bank Transfer (Laos)",
  "Bank Transfer (Middle East)",
  "Bank transfer (PH)",
  "Bank Transfer (Romania)",
  "Bank Transfer (Taiwan)",
  "Bank Transfer (Turkey)",
  "Bank Transfer (Vietnam)",
  "Bank Transfer Peru",
  "Bank Transilvania",
  "Bank Vlasnyi Rakhunok",
  "Bankera",
  "BankOfBaku",
  "Banorte",
  "BANPAÍS",
  "Banpais Honduras",
  "Banplus",
  "Banque de développement local (BDL)",
  "Banque de l'agriculture et du développement rural (BADR)",
  "Banque du Caire",
  "Banque extérieure d’Algérie (BEA)",
  "Banque Misr",
  "Banque nationale d’Algérie (BNA)",
  "Banque Zitouna",
  "Banreservas",
  "Banrural",
  "Bantrab",
  "banxy- La Banque Mobile",
  "BasisBank",
  "BBVA",
  "BBVA Uruguay",
  "BCAv",
  "BCA Syariah",
  "BCEL",
  "BCR Bank",
  "BCS Bank",
  "Belize Bank",
  "Belo app",
  "BenefitPayv",
  "BEYON Money",
  "BGFIBank",
  "BGZ BNP Paribas",
  "BigPay",
  "Billetera Movil Banpro",
  "Billetera Personal",
  "Bitera",
  "Bitsika",
  "Bizum",
  "bKash",
  "Blik",
  "BLOM Bank",
  "Blu",
  "BMCE Bank",
  "BMO",
  "BNC Banco Nacional de Crédito",
  "BNP Paribas",
  "Bogd Bank",
  "BOS Bank",
  "Boubyan Bank (K.S.C) (Boubyan)",
  "BRD Bank",
  "BSB Bank",
  "BTA Bank",
  "Budapest Bank",
  "Bundle",
  "Bunq",
  "Burgan Bank (K.S.C) (Burgan)",
  "Byblos Bank",
  "C&WJ Co-operative Credit Union",
  "Cairo Amman Bank",
  "Caisse d′Epargne",
  "CaixaBank (Spain)",
  "CAKE",
  "CalBank",
  "Canadia",
  "Capital Bank",
  "Capitec Bank",
  "Capitron Bank",
  "Cartes Bancaires",
  "CartuBank",
  "Cash app",
  "Cash Deposit to Bank",
  "Cash in Person",
  "Cashpack",
  "CashU",
  "CB Pay",
  "CBE",
  "CBE Birr",
  "CEC",
  "CenterCredit Bank",
  "Central Bank of the Bahamas",
  "Central Bank of Trinidad and Tobago",
  "Central Bank of Uruguay",
  "Česká spořitelna",
  "CFG BANK",
  "China Bank",
  "Chinggis Khaan Bank",
  "Chipper Cash",
  "Chivo wallet",
  "CIB",
  "CIB Bank",
  "CIBC",
  "CIH Bank",
  "CIMB Niaga",
  "CIMB Philippines",
  "Citi Handlowy",
  "Citibanamex",
  "Citibank (Russia)",
  "Citibank Nigeria Limited",
  "CliQ",
  "Co-Operative Bank Of Kenya",
  "Cobru",
  "Coinpay",
  "Coins.ph",
  "Commercial bank Kyrgyzstan",
  "ConverseBank",
  "Corporate Bank Of Oromia",
  "cpay",
  "Credit Agricole",
  "Credit Bank of Peru",
  "Crédit Banque Populaire du Maroc",
  "Crédit du Maroc",
  "Credit Europe Bank (Russia)",
  "Credit Libanais",
  "Crédit populaire d'Algérie (CPA)",
  "Credo Bank",
  "Crystalbank",
  "ČSOB",
  "DANA",
  "Danamon Bank",
  "Dashen",
  "Daviplata",
  "Davivienda S.A",
  "DayhanBank",
  "DBS",
  "DemirBank",
  "Denizbank",
  "DIB: Dubai Islamic Bank",
  "DitoBanx El Salvador",
  "Doha Bank",
  "DSK Bank",
  "Dukascopy Bank",
  "Dushanbe City Bank",
  "E-Kwanza",
  "E-Kyash",
  "Easypaisa-PK Only",
  "EasyPay",
  "Ecobank",
  "Efecty",
  "EIB: Emirates Islamic Bank",
  "Elcart",
  "Emirates NBD",
  "EQ Bank",
  "Equity Bank",
  "Erste Bank",
  "Esewa",
  "Eurasian Bank",
  "EVC Plus",
  "Evocabank",
  "Expressbank",
  "eZCash",
  "EziPay",
  "Facebank International",
  "Fast Bank",
  "Faster Payments",
  "FastPay",
  "FCMB",
  "Fibabanka",
  "Fibank",
  "Fidelity Bank",
  "Fidelity Bank Plc",
  "Financiera Solar",
  "Finca Bank",
  "FinComBank",
  "Finexpar",
  "Fio banka",
  "First Bank Of Nigeria",
  "First Citizens Bank",
  "First Iraqi Bank",
  "FirstCaribbean International Bank Ltd",
  "Fiwind",
  "Flip",
  "FNB-ewallet",
  "ForteBank",
  "Forward Bank",
  "Foxpay",
  "Fransabank",
  "Free Money",
  "Freedom Bank",
  "FRI Guatemala",
  "Garanti",
  "Gcash",
  "GCB Bank",
  "Genie",
  "GEO Pay",
  "Girocard",
  "Global Bank Panama",
  "Global66",
  "Globus Bank Limited",
  "Golomt Bank",
  "GoMoney",
  "Google Pay (GPay)",
  "GoPay",
  "GoTyme Bank",
  "GTBank",
  "Gulf Bank (K.S.C) (GBK)",
  "HalkBank",
  "Halyk Bank",
  "Hamkorbank",
  "Hana Bank",
  "Heritage Bank Plc",
  "Hibret Bank",
  "Home Credit Bank (Russia)",
  "Home Credit Kazakhstan",
  "HSBC Bank Egypt",
  "HSBC Bank Middle East Limited - Bahrain",
  "HSBC Bank Middle East- UAE",
  "HSBC Oman",
  "HSBC Uruguay",
  "Humans",
  "Humo",
  "Hype",
  "IDBank",
  "Idea Bank",
  "iDEAL",
  "Idram",
  "IME Pay",
  "IMPS",
  "Inecobank",
  "InfinBank",
  "ING",
  "Instant Bank Transfer",
  "Instant Transfer",
  "InstaPay",
  "Interac e-Transfer",
  "Interbank",
  "Interfisa Banco",
  "International Bank of Tajikistan",
  "International Wire (SWIFT)",
  "Ipak Yuli Bank",
  "Ipoteka Bank",
  "İŞBANK",
  "Islamic Bank of Afghanistan",
  "Itaú Brazil",
  "Itaú Uruguay",
  "Izibank",
  "Jaiz Bank Plc",
  "Jenius PayMe",
  "JETCOPay",
  "JKO Payment (Direct)",
  "JKO Transfer",
  "Jordan Islamic Bank",
  "Jordan Kuwait Bank",
  "Jysan Bank",
  "K&H Bank",
  "Kapitalbank",
  "KASH Guatemala",
  "Kaspi Bank",
  "Kazpost",
  "KBZPay",
  "Keremet Bank",
  "Keystone Bank",
  "Khalti",
  "Khan Bank",
  "Khipu",
  "KHQR",
  "KICB",
  "Komo Bank",
  "Kompanion Bank",
  "KoronaPay",
  "Korti milli",
  "KredoBank",
  "Kuda Bank NG",
  "Kuveyt Turk",
  "Kuwait Finance House (KFH)",
  "La Banque postale",
  "Landbank of the Philippines",
  "Lemon Cash",
  "LendMN",
  "Leobank",
  "Liberty Bank",
  "Lightning UPI",
  "Ligo",
  "LINE Bank",
  "LINE Pay",
  "LinkAja",
  "Liv. KSA",
  "Lloyds Bank",
  "LOTUS BANK",
  "M Money Laos",
  "M Pay",
  "M-pesa (Vodafone)",
  "M-PESA Kenya (Safaricom)",
  "M-pesa Paybill",
  "M-Pitesan",
  "m10",
  "MACH",
  "MAIB",
  "Mandiri Pay",
  "Maybank",
  "Maza",
  "mBank",
  "Meezan Bank",
  "Mercadopago",
  "Mercantil",
  "Mercantil Bank Panama",
  "Metropolitan Bank of the Philippines",
  "MICB",
  "Mikrokreditbank",
  "Millennium",
  "MKB Bank",
  "MNC Bank",
  "Mobikwik",
  "MobiMoney",
  "Modo",
  "MoMo",
  "Moncash",
  "MONETA Money Bank",
  "Moneygram",
  "Mongol Chat",
  "Monobank",
  "Monpay",
  "Mony",
  "Monzo",
  "Moov Money",
  "Movii",
  "MTBank",
  "MTN Mobile Money",
  "MTS-Bank",
  "Muganbank",
  "Multibank Panama",
  "MyZaka",
  "N26",
  "Nagad",
  "Naranja X",
  "NassWallet",
  "National Bank of Abu Dhabi FAB",
  "National Bank of Egypt (NBE)",
  "National Bank of Kuwait (K.S.C) (NBK)",
  "National Bank of Oman",
  "National Bank of Yemen",
  "National Investment Bank of Mongolia",
  "NayaPay",
  "NCB Bank",
  "Nedbank",
  "NEO",
  "NEO Pay Iraq",
  "Nequi",
  "Neteller",
  "Nobu Bank",
  "NOVI Guatemala",
  "Nuars",
  "Nurbank",
  "O!Money",
  "OCA Blue",
  "OCBC NISP",
  "OLDUBIL",
  "Onepay",
  "Opay",
  "Optima Bank",
  "Orange Money - OM",
  "Orange Money - Sierra Leone",
  "Orienbank",
  "Oschadbank",
  "OSKO",
  "OSON",
  "OTP BANK",
  "OVO",
  "OXXO",
  "Oy!",
  "Ozan",
  "Ozon Bank",
  "Pago Movil",
  "PagSeguro",
  "Palmpay",
  "Papara",
  "Paritet Bank",
  "Pasha Bank",
  "Payby",
  "Payeer",
  "PayGram",
  "PayID",
  "Paymaya",
  "Payme.io",
  "Paynet",
  "PayPro",
  "Paysend.com",
  "Paysera",
  "Paytm",
  "Perfect Money",
  "Permata Me",
  "Philippines National Bank (PNB)",
  "PhonePe",
  "Pi Pay",
  "PicPay",
  "Pipol Pay",
  "Pix",
  "PKO Bank",
  "Plin",
  "Polaris Bank Limited",
  "Post Bank",
  "Postepay",
  "Pravex Bank",
  "Premium Bank",
  "PremiumTrust NG",
  "Prex",
  "PriorBank",
  "Privat Bank (Universal Card)",
  "ProCredit Bank",
  "Produbanco",
  "Providus Bank Limited",
  "Provincial",
  "PUMB",
  "Pyypl",
  "Qatar International Islamic Bank QIIB",
  "Qatar Islamic Bank QIB",
  "Qatar National Bank QNB",
  "Qik Banco Digital",
  "Qishloq Qurilish Bank",
  "QIWI",
  "QNB",
  "QPay",
  "全盈+PAY",
  "Raast",
  "Rabitabank",
  "Raiffeisen Bank Aval",
  "Raiffeisenbank",
  "Ravnaq-bank",
  "RBC Royal Bank",
  "Reba",
  "Recarga Pines",
  "Red Pagos",
  "Renaissance Credit Bank",
  "Revolut",
  "Riyad Bank",
  "Rizal Commercial Banking Corporation",
  "Rocket",
  "Rocketbank",
  "RosBank",
  "Royal Bank of Canada Bahamas",
  "RSK Bank",
  "Russian Standard Bank",
  "SadaPay",
  "SalamPay",
  "Sanoatsodirotbank",
  "Santander Mexico",
  "Santander Poland",
  "Satispay",
  "Satoshi Tango",
  "Saudi National Bank (AlAhli Bank)",
  "Scotia Bank Bahamas",
  "Scotia Bank Trinidad",
  "Scotiabank Colpatria",
  "Scotiabank Costa Rica",
  "Scotiabank Jamaica",
  "Scotiabank Panama",
  "Scotiabank Peru",
  "Scotiabank Uruguay",
  "SEA Bank",
  "Security Bank",
  "Sense SuperApp",
  "SEPA (EU) bank transfer",
  "SEPA Instant",
  "SettlePay",
  "Shopee (Taiwan)",
  "ShopeePay-SEA",
  "SIB: Sharjah Islamic Bank",
  "Silvergate Bank",
  "Simply",
  "Sinarmas",
  "Skrill (Moneybookers)",
  "SmartPay",
  "Social Pay",
  "Societe Generale",
  "Société Générale Commercial Maroc",
  "Sofort",
  "Sohar International",
  "SoliPagos",
  "Spenn",
  "Spitamen Bank",
  "Sportbank",
  "SQB Bank",
  "Stanbic Bank",
  "Standard Chartered Bank",
  "Starling Bank",
  "StarPay",
  "State Bank",
  "Statusbank",
  "stc pay",
  "Sterling Bank",
  "STP",
  "Suntrust Bank NG",
  "SuperUp",
  "Swish",
  "Switch",
  "Swordpay",
  "Tadhamon International Islamic Bank",
  "Tangerine bank",
  "Tap",
  "Tascombank",
  "TBC Bank",
  "TD Bank",
  "Technobank",
  "telda",
  "Tele Birr",
  "Tenge Bank",
  "Tenpo",
  "Terabank",
  "The Arab Investment Company S.A.A.",
  "The Saudi British Bank (SABB)",
  "Tigo Money",
  "Tigo Pesa",
  "Tinkoff",
  "Titan Trust Bank",
  "TK Bank",
  "TMRW by UOB",
  "Tonik Bank",
  "Towerbank",
  "Trade and Development Bank",
  "Trans Bank",
  "Transferencia ACH (Panamá)",
  "Transferencia Bancaria Costa Rica",
  "Transferencia Bancaria El Salvador",
  "Transferencia Bancaria Guatemala",
  "Transferencia Bancaria Honduras",
  "Transferencia Bancaria Nicaragua",
  "Transfers with specific bank",
  "TrastBank",
  "True Money",
  "True Money (Cambodia)",
  "Trust",
  "Tu Dinero Ya (Banco Plaza)",
  "Tunisian banking company",
  "TuranBank",
  "Turkiye Finans Participation Bank",
  "TurkmenbasyBank",
  "Turon Bank",
  "U-money",
  "uabpay",
  "Uala",
  "Uala",
  "Ubii Pagos",
  "Ukreximbank",
  "Ukrgasbank",
  "Ukrsibbank",
  "Unibank",
  "UniCredit",
  "UniCredit",
  "UniCredit Bulbank",
  "Union Bank of Nigeria",
  "Union Digital Bank",
  "UnionBank of the Philippines",
  "UnionPay",
  "Unired",
  "United Bank for Africa Plc",
  "United Bank Limited",
  "United Bulgarian Bank (UBB)",
  "Unity Bank Plc",
  "Uno Bank",
  "Upaisa",
  "Uphold",
  "UPI",
  "UPI QR",
  "Uralsib Bank",
  "urpay",
  "Utoppia",
  "Uzbek National Bank",
  "Uzcard",
  "VakifBank",
  "VeloBank",
  "Venmo",
  "Victoriabank",
  "Viettel Money",
  "VinID",
  "Vipps",
  "VisaNet Guatemala",
  "Vision Banco",
  "Vita Wallet",
  "Vivid Money",
  "VNPAY",
  "VNPT Money",
  "Vodafone cash",
  "Wally Tech",
  "Wallyt",
  "Wave Mobile Money",
  "Wave Money",
  "WavePay",
  "WeChat",
  "Wegagen Bank",
  "Wema Bank",
  "Western Union",
  "whish MONEY",
  "Wilobank",
  "Wing Money",
  "Wise",
  "Wise Instant",
  "WorldRemit",
  "XacBank",
  "Xalq Bank",
  "Yap! (BNI)",
  "Yape",
  "Yelo Bank",
  "Yemen Commercial Bank",
  "ZainCash",
  "ZainCash - Business",
  "ZaloPay",
  "Zelle",
  "ZEN",
  "Zenith Bank",
  "Zepter Bank",
  "Zinli",
  "Ziraat",
  "Юmoney",
];
